// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV5_iPfvcr6r8XTDp1Nvcz0jkepkka_u8',
    appId: '1:415249705316:web:8a3bc7fd1c38adda7a7271',
    messagingSenderId: '415249705316',
    projectId: 'thetallesthobbit-e4d1c',
    authDomain: 'thetallesthobbit-e4d1c.firebaseapp.com',
    storageBucket: 'thetallesthobbit-e4d1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NLWUaJE3UeC4XO3XOQpwFia8RaGWTqA',
    appId: '1:415249705316:android:436e4aeb240b40937a7271',
    messagingSenderId: '415249705316',
    projectId: 'thetallesthobbit-e4d1c',
    storageBucket: 'thetallesthobbit-e4d1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBrQHscCIXq5NFlagsz2-BuVYX0NixIi8',
    appId: '1:415249705316:ios:eab7155bf0833c607a7271',
    messagingSenderId: '415249705316',
    projectId: 'thetallesthobbit-e4d1c',
    storageBucket: 'thetallesthobbit-e4d1c.appspot.com',
    iosBundleId: 'com.example.thetallesthobbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBrQHscCIXq5NFlagsz2-BuVYX0NixIi8',
    appId: '1:415249705316:ios:d212562ab8a6c8d17a7271',
    messagingSenderId: '415249705316',
    projectId: 'thetallesthobbit-e4d1c',
    storageBucket: 'thetallesthobbit-e4d1c.appspot.com',
    iosBundleId: 'com.example.thetallesthobbit.RunnerTests',
  );
}
